apiVersion: v1
kind: Service
metadata:
  name: distance-sensor
  labels:
    app: distance-sensor
spec:
  type: NodePort
  ports:
    - port: 9207
      protocol: TCP
      targetPort: 9207
      nodePort: 30333
  selector:
    app: distance-sensor