apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: distance-sensor
  labels:
    app: distance-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distance-sensor
  template:
    metadata:
      labels:
        app: distance-sensor
    spec:
      containers:
      - image: geekdave/prometheus_hcsr04_exporter:v0.0.2
        name: distance-sensor
        ports:
        - containerPort: 9207
          protocol: TCP
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_RAWIO
      restartPolicy: Always
      nodeSelector:
        region: garage
